version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      NODE_ENV: production
      MONGODB_URI: mongodb+srv://yakobyte:AU5ZldseqnrEtMUK@obaol-cluster.oq0ij.mongodb.net/oboal
      JWT_SECRET: dev-secret
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: