export const NotificationTypes = {
  INQUIRY_CREATED: "INQUIRY_CREATED",
  INQUIRY_ASSIGNED: "INQUIRY_ASSIGNED",
  INQUIRY_STATUS_CHANGED: "INQUIRY_STATUS_CHANGED",
  INQUIRY_SUPPLIER_ACCEPTED: "INQUIRY_SUPPLIER_ACCEPTED",
  ORDER_CONVERTED: "ORDER_CONVERTED",
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_STAGE_CHANGED: "ORDER_STAGE_CHANGED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  ORDER_MILESTONE_UPDATED: "ORDER_MILESTONE_UPDATED",
  INVENTORY_CREATED: "INVENTORY_CREATED",
  INVENTORY_RESERVED: "INVENTORY_RESERVED",
  INVENTORY_RELEASED: "INVENTORY_RELEASED",
  INVENTORY_CONSUMED: "INVENTORY_CONSUMED",
  INVENTORY_LOW_STOCK: "INVENTORY_LOW_STOCK",
  BID_SUBMITTED: "BID_SUBMITTED",
  BID_UPDATED: "BID_UPDATED",
  BID_AWARDED: "BID_AWARDED",
  VARIANT_RATE_LIVE: "VARIANT_RATE_LIVE",
  EXECUTION_TASKS_CREATED: "EXECUTION_TASKS_CREATED",
  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  APPROVAL_APPROVED: "APPROVAL_APPROVED",
  GENERAL_MESSAGE: "GENERAL_MESSAGE",
} as const;

export const NotificationEntityTypes = {
  INQUIRY: "INQUIRY",
  ORDER: "ORDER",
  INVENTORY: "INVENTORY",
  VARIANT_RATE: "VARIANT_RATE",
  APPROVAL: "APPROVAL",
  SYSTEM: "SYSTEM",
} as const;

export type NotificationType = (typeof NotificationTypes)[keyof typeof NotificationTypes];
export type NotificationEntityType = (typeof NotificationEntityTypes)[keyof typeof NotificationEntityTypes];
