export interface IAssociateCompany {
  _id: string;
  name: string;
  email: string;
  phone: string;
  phoneCountryCode?: string;
  phoneNational?: string;
  location?: {
    latitude?: number;
    longitude?: number;
    label?: string;
  };
  phoneSecondary: string;
  phoneSecondaryCountryCode?: string;
  phoneSecondaryNational?: string;
  serviceCapabilities?: string[];
  isQualityLabListed?: boolean;
  labDisplayName?: string;
  labContactEmail?: string;
  labContactPhone?: string;
  labContactPhoneSecondary?: string;
  labTests?: string[];
  labCertifications?: string[];
  labSpecifications?: string[];
  labAcceptedItems?: string[];
  labNotes?: string;
  isActive?: boolean;
  isDeleted?: boolean;
  supervisor?: string;
  logo?: string;
  banner?: string;
  description?: string;
  aboutUs?: string;
  address?: string;
  website?: string;
  socialLinks?: {
    linkedin?: string;
    facebook?: string;
    twitter?: string;
    instagram?: string;
  };
  tags?: string[];
  subdomain?: string;
  customDomain?: string;
  isWebsiteLive?: boolean;
  gstin?: string;
  legalRegistrationNumber?: string;
  legalComplianceInfo?: string;
  registrationStatus?: "PENDING_REVIEW" | "APPROVED" | "REJECTED";
  isApproved?: boolean;
  approvedAt?: Date;
  approvedBy?: string;
  reviewNotes?: string;
}

export interface ICreateAssociateCompany {
  name: string;
  email: string;
  phone: string;
  phoneCountryCode?: string;
  phoneNational?: string;
  location?: {
    latitude?: number;
    longitude?: number;
    label?: string;
  };
  phoneSecondary: string;
  phoneSecondaryCountryCode?: string;
  phoneSecondaryNational?: string;
  serviceCapabilities?: string[];
  isQualityLabListed?: boolean;
  labDisplayName?: string;
  labContactEmail?: string;
  labContactPhone?: string;
  labContactPhoneSecondary?: string;
  labTests?: string[];
  labCertifications?: string[];
  labSpecifications?: string[];
  labAcceptedItems?: string[];
  labNotes?: string;
  isActive?: boolean;
  isDeleted?: boolean;
  supervisor?: string;
  logo?: string;
  banner?: string;
  description?: string;
  aboutUs?: string;
  address?: string;
  website?: string;
  socialLinks?: {
    linkedin?: string;
    facebook?: string;
    twitter?: string;
    instagram?: string;
  };
  tags?: string[];
  subdomain?: string;
  customDomain?: string;
  isWebsiteLive?: boolean;
  gstin?: string;
  legalRegistrationNumber?: string;
  legalComplianceInfo?: string;
  registrationStatus?: "PENDING_REVIEW" | "APPROVED" | "REJECTED";
  isApproved?: boolean;
  approvedAt?: Date;
  approvedBy?: string;
  reviewNotes?: string;
}

export interface IUpdateAssociateCompany {
  name?: string;
  email?: string;
  phone?: string;
  phoneCountryCode?: string;
  phoneNational?: string;
  location?: {
    latitude?: number;
    longitude?: number;
    label?: string;
  };
  phoneSecondary?: string;
  phoneSecondaryCountryCode?: string;
  phoneSecondaryNational?: string;
  serviceCapabilities?: string[];
  isQualityLabListed?: boolean;
  labDisplayName?: string;
  labContactEmail?: string;
  labContactPhone?: string;
  labContactPhoneSecondary?: string;
  labTests?: string[];
  labCertifications?: string[];
  labSpecifications?: string[];
  labAcceptedItems?: string[];
  labNotes?: string;
  isActive?: boolean;
  isDeleted?: boolean;
  supervisor?: string;
  logo?: string;
  banner?: string;
  description?: string;
  aboutUs?: string;
  address?: string;
  website?: string;
  socialLinks?: {
    linkedin?: string;
    facebook?: string;
    twitter?: string;
    instagram?: string;
  };
  tags?: string[];
  subdomain?: string;
  customDomain?: string;
  isWebsiteLive?: boolean;
  gstin?: string;
  legalRegistrationNumber?: string;
  legalComplianceInfo?: string;
  registrationStatus?: "PENDING_REVIEW" | "APPROVED" | "REJECTED";
  isApproved?: boolean;
  approvedAt?: Date;
  approvedBy?: string;
  reviewNotes?: string;
}
