import { Types } from "mongoose";

export interface IAssociate {
  _id: string;
  name: string;
  email: string;
  designation?: Types.ObjectId | string | null;
  phone: string;
  phoneCountryCode?: string;
  phoneNational?: string;
  phoneSecondary?: string;
  phoneSecondaryCountryCode?: string;
  phoneSecondaryNational?: string;
  associateInterests?: string[];
  tradeMode?: "BUY" | "SELL" | "BOTH" | "SERVICE";
  associateCompany?: Types.ObjectId | string | null; // Assuming this is stored as the ID of the AssociateCompany
  hasCompany?: boolean;
  companyMode?: "existing" | "new" | "none";
  address?: string;
  geoType?: "INDIAN" | "INTERNATIONAL";
  country?: Types.ObjectId | string | null;
  state?: Types.ObjectId | string | null;
  district?: Types.ObjectId | string | null;
  division?: Types.ObjectId | string | null;
  pincodeEntry?: Types.ObjectId | string | null;
  password: string;
  authProvider?: "LOCAL" | "GOOGLE";
  googleSub?: string | null;
  googleEmailVerified?: boolean;
  failedLoginAttempts?: number;
  loginLockedUntil?: Date | null;
  lastFailedLoginAt?: Date | null;
  loginLockoutLevel?: number;
  isActive?: boolean;
  isDeleted?: boolean;
  isEmailVerified?: boolean;
  isPhoneVerified?: boolean;
  isOneToOneVerified?: boolean;
  isCompanyVerified?: boolean;
  registrationStatus?: "PENDING_REVIEW" | "APPROVED" | "REJECTED";
  approvalRequestedAt?: Date | null;
  reviewNotes?: string;
  onboardingContactPreference?: "phone" | "email";
  onboardingContactNotes?: string;
  registrationSource?: string;
  referralCode?: string;
  onboardingComplete?: boolean;
  dashboardTutorialStatus?: "PENDING" | "SKIPPED" | "COMPLETED";
  dashboardTutorialUpdatedAt?: Date | null;
  lastSeenAt?: Date | null;
  presenceUpdatedAt?: Date | null;
  presenceSource?: "AUTH_REQUEST" | "HEARTBEAT" | null;
}

export interface ICreateAssociate {
  name: string;
  email: string;
  phone: string;
  phoneCountryCode?: string;
  phoneNational?: string;
  phoneSecondary?: string;
  phoneSecondaryCountryCode?: string;
  phoneSecondaryNational?: string;
  associateInterests?: string[];
  tradeMode?: "BUY" | "SELL" | "BOTH" | "SERVICE";
  associateCompany?: Types.ObjectId | string | null; // ID of the AssociateCompany
  designation?: Types.ObjectId | string | null;
  hasCompany?: boolean;
  companyMode?: "existing" | "new" | "none";
  address?: string;
  geoType?: "INDIAN" | "INTERNATIONAL";
  country?: Types.ObjectId | string | null;
  state?: Types.ObjectId | string | null;
  district?: Types.ObjectId | string | null;
  division?: Types.ObjectId | string | null;
  pincodeEntry?: Types.ObjectId | string | null;
  password: string;
  authProvider?: "LOCAL" | "GOOGLE";
  googleSub?: string | null;
  googleEmailVerified?: boolean;
  failedLoginAttempts?: number;
  loginLockedUntil?: Date | null;
  lastFailedLoginAt?: Date | null;
  loginLockoutLevel?: number;
  isActive?: boolean;
  isDeleted?: boolean;
  isEmailVerified?: boolean;
  isPhoneVerified?: boolean;
  isOneToOneVerified?: boolean;
  isCompanyVerified?: boolean;
  registrationStatus?: "PENDING_REVIEW" | "APPROVED" | "REJECTED";
  approvalRequestedAt?: Date | null;
  reviewNotes?: string;
  onboardingContactPreference?: "phone" | "email";
  onboardingContactNotes?: string;
  registrationSource?: string;
  referralCode?: string;
  onboardingComplete?: boolean;
  dashboardTutorialStatus?: "PENDING" | "SKIPPED" | "COMPLETED";
  dashboardTutorialUpdatedAt?: Date | null;
  lastSeenAt?: Date | null;
  presenceUpdatedAt?: Date | null;
  presenceSource?: "AUTH_REQUEST" | "HEARTBEAT" | null;
}

export interface IUpdateAssociate {
  name?: string;
  email?: string;
  phone?: string;
  phoneCountryCode?: string;
  phoneNational?: string;
  phoneSecondary?: string;
  phoneSecondaryCountryCode?: string;
  phoneSecondaryNational?: string;
  associateInterests?: string[];
  tradeMode?: "BUY" | "SELL" | "BOTH" | "SERVICE";
  designation?: Types.ObjectId | string | null;
  associateCompany?: Types.ObjectId | string | null; // ID of the AssociateCompany
  hasCompany?: boolean;
  companyMode?: "existing" | "new" | "none";
  address?: string;
  geoType?: "INDIAN" | "INTERNATIONAL";
  country?: Types.ObjectId | string | null;
  state?: Types.ObjectId | string | null;
  district?: Types.ObjectId | string | null;
  division?: Types.ObjectId | string | null;
  pincodeEntry?: Types.ObjectId | string | null;
  password?: string;
  authProvider?: "LOCAL" | "GOOGLE";
  googleSub?: string | null;
  googleEmailVerified?: boolean;
  isActive?: boolean;
  isDeleted?: boolean;
  isEmailVerified?: boolean;
  isPhoneVerified?: boolean;
  isOneToOneVerified?: boolean;
  isCompanyVerified?: boolean;
  registrationStatus?: "PENDING_REVIEW" | "APPROVED" | "REJECTED";
  approvalRequestedAt?: Date | null;
  reviewNotes?: string;
  onboardingContactPreference?: "phone" | "email";
  onboardingContactNotes?: string;
  registrationSource?: string;
  referralCode?: string;
  onboardingComplete?: boolean;
  dashboardTutorialStatus?: "PENDING" | "SKIPPED" | "COMPLETED";
  dashboardTutorialUpdatedAt?: Date | null;
  lastSeenAt?: Date | null;
  presenceUpdatedAt?: Date | null;
  presenceSource?: "AUTH_REQUEST" | "HEARTBEAT" | null;
}
